services:
  writebook:
    build: .
    # hoặc dùng image có sẵn:
    # image: ghcr.io/basecamp/writebook:latest

    container_name: writebook

    ports:
      - "3000:80" # local dev on http://localhost:3000
      # - "8080:80" # optional: use http://localhost:8080 instead
      # - "443:443"   # nếu dùng SSL built-in

    volumes:
      - .:/app
      # - writebook_data:/rails/storage

    environment:
      RAILS_ENV: development
      DISABLE_SSL: "true"
      SECRET_KEY_BASE: 0203c81c0d0eb7b729b1be9c391e3ef541d23e1af3d23f2e95117b694aca22773baa945577c085d474f62ffa734828de12475ac868b6a1964e47f8d9cfe02578

      # optional (nếu dùng SSL)
      # SSL_DOMAIN: your-domain.com
      # DISABLE_SSL: "true"

    restart: unless-stopped

volumes:
  writebook_data:
